blank_issues_enabled: false
contact_links:
  - name: Questions about Icemyst
    url: https://github.com/icemyst/hexo-theme-icemyst/discussions
    about: 一些使用問題請到 Discussion 詢問。 Please ask questions in Discussion.

  - name: Butterfly Q&A
    url: https://butterfly.js.org/posts/98d20436/
    about: Butterfly Q&A

  - name: Telegram
    url: https://t.me/icemyst
    about: 'Official Telegram Group'

  - name: QQ 群
    url: https://jq.qq.com/?_wv=1027&k=617Ln51sCmh-QkaIl8cYf03kXdT0f8vo
    about: '群號 347512871'

